### ISSUE TITLE
doppler.exe flagged as suspicious, checksums don't match

### ISSUE THREAD

**Issue by philwilliamson** [DopplerHQ/scoop-doppler#1]
I've installed the Doppler CLI on my Windows machine using Scoop and recently updated it using Scoop to v3.38.0. When I tried to run `doppler setup`, Norton blocked the executable from accessing network resources. 

I initially thought it was a false positive and allowed it, but have since done a bit more investigating. I used certutil to checksum the blocked executable (found at `c:\Users\<USER>\scoop\apps\doppler\3.38.0\doppler.exe` ) and discovered the sha256 hash differs from the hash in the `doppler.json` file of this repo:
Hash in the `doppler.json` of this repo:
`594c747c8d6d7c41ecc0e92adfa33253976bd0126f18f358512c19d66f577a6e`
Hash I found using certutil:
`58f917c9c352141199ee0ab026f2003f3adbf9fe73e8e21c0cc296f1b6030c27`

I'm unsure if this is significant as I don't know if the hash in the package's `.json` file is meant for checksums like this. I also uploaded the executable found at that path above to Intezer and VirusTotal and both flagged it as malicious. Am I right to be suspicious?

**Comment by Piccirello** [comment]
This appears to be a false positive.

The hash in this repo's `package.json` is for the `doppler_3.38.0_windows_amd64.zip` zip file, which matches the hash in the CLI's [checksum.txt](https://github.com/DopplerHQ/cli/releases/tag/3.38.0) (`594c747c8d6d7c41ecc0e92adfa33253976bd0126f18f358512c19d66f577a6e`). Once unzipped, `doppler.exe` has a hash of `58f917c9c352141199ee0ab026f2003f3adbf9fe73e8e21c0cc296f1b6030c27`, which matches what you're seeing on your machine.

I've uploaded a known good version of `doppler.exe` to [VirusTotal](https://www.virustotal.com/gui/file/58f917c9c352141199ee0ab026f2003f3adbf9fe73e8e21c0cc296f1b6030c27/detection), which produces 2 detections. The first is for Cynet, which reports "Malicious (score: 100)", and the second is MaxSecure, which reports "Trojan.Malware.300983.susgen". The Doppler CLI does not currently use functionality from any packages with [known CVEs](https://github.com/DopplerHQ/cli/security/dependabot), so I'm not sure what these tools are detecting. In any case, you're safe to ignore this.

**Comment by philwilliamson** [comment]
Ah, my mistake getting confused about the hashes. That in combination with the false positives caused me to worry. I appreciate you checking on your end.

That last link you were sharing unfortunately does not work for me. Should I look to the [DopplerHQ/cli repo's security tab](https://github.com/DopplerHQ/cli/security) for security advisories? Or anywhere else?
